//This is the redux code for action type
export const ActionTypes = {
    SET_ATMS: "SET_ATMS",
    SELECTED_ATM: "SELECTED_ATM",
    SELECTED_DEVICE: "SELECTED_DEVICE",
    SELECTED_MEDIA: "SELECTED_MEDIA",
    SELECTED_CASH: "SELECTED_CASH",
    SELECTED_VENDOR: "SELECTED_VENDOR",
    SELECTED_CUSTODIAN: "SELECTED_CUSTODIAN",
    SELECTED_ATM_MYSQL: "SELECTED_ATM_MYSQL",
    SET_ALL_STATE: "SET_ALL_STATE",
    /*  SET_ALL_REGION: "SET_ALL_REGION", */
    REMOVE_SELECTED_ATM: "REMOVE_SELECTED_ATM",




    

/*-------------- brand--------------*/
    SET_ALL_BRAND: "SET_ALL_BRAND",
    SET_ALL_VARIANTS:"SET_ALL_VARIANTS",
/*-------------- brand--------------*/




    SET_ALL_USERS: "SET_ALL_USERS",
    SET_ALL_CUSTODIANS: "SET_ALL_CUSTODIANS",
    SET_ALL_VENDORS: "SET_ALL_VENDORS",
    SET_ALL_LOGS: "SET_ALL_LOGS",
    SET_ALL_BRANCHES: "SET_ALL_BRANCHES",
    COUNT_ATM: "COUNT_ATM",
    SET_ALL_REGIONALMANAGER: "SET_ALL_REGIONALMANAGER",
    SET_ALL_TICKET: "SET_ALL_TICKET",
    SET_SELECTED_USER: "SET_SELECTED_USER"
}